language: c
addons:
    apt:
        packages:
            - ninja-build
			- libpng-dev
matrix:
    include:
        - os: linux
          compiler: gcc
          env: CONFIGURATION="Release"
        - os: linux
          compiler: clang
          env: CONFIGURATION="Release"
        - os: osx
          compiler: clang
          env: CONFIGURATION="Release" MACOSX_ARCH=i386
        - os: osx
          compiler: clang
          env: CONFIGURATION="Release" MACOSX_ARCH=x86_64
          
        - os: linux
          compiler: gcc
          env: CONFIGURATION="Debug"
        - os: linux
          compiler: clang
          env: CONFIGURATION="Debug"
        - os: osx
          compiler: clang
          env: CONFIGURATION="Debug" MACOSX_ARCH=i386
        - os: osx
          compiler: clang
          env: CONFIGURATION="Debug" MACOSX_ARCH=x86_64
install:
    - ./ci/travis/install.sh
before_script:
    - ./ci/travis/before_script.sh
script:
    - ./ci/travis/script.sh
